[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.55.1"
current_dir = "0.1.2"
itertools = "0.14.0"
lazy_static = "1.5.0"
nom = "8.0.0"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
structopt = "0.3.26"
